site_name: Citrix Common Connection Manager SDK
site_description: Reference guide for the Citrix Common Connection Manager SDK
theme_dir: citrix-sdk
repo_url:
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      anchorlink: True

pages:
- Overview: index.md
- Using the SDK: using-the-sdk.md
- CCM SDK API Reference: reference.md
- Appendix: appendix.md
